version: '3.8'
services:
  mysql-db:
    container_name:  mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --sql_mode=
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DATABSE_PASSWORD
    ports:
      - $DATABSE_LOCAL_PORT:$DATABSE_DOCKER_PORT
    volumes:
      - mysql-db:/var/lib/mysql
      - ./mysql-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default  

  crud-user:
    container_name: crud-user
    depends_on:
      - mysql-db
    build:
      context: ./crud-user
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NESTJS_PROJECT_DOCKER_PORT:$NESTJS_PROJECT_DOCKER_PORT
    environment:
      - DB_TYPE=$DATABSE_TYPE
      - DB_HOST=$DATABSE_HOST
      - DB_USER=$DATABSE_USER
      - DB_PASSWORD=$DATABSE_PASSWORD
      - DB_DATABASE=$DATABSE_DATABASE
      - DB_PORT=$DATABSE_DOCKER_PORT
      - API_URL=$API_URL
      - API_PORT=$NESTJS_PROJECT_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./crud-user:/app
      - /app/node_modules
    networks:
      - default   
            
volumes: 
  mysql-db:      